name: CI using github actions & docker

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build -t cyoobin/docker-react-app -f Dockerfile.dev .

      - name: Run tests
        run: |
          docker run -e CI=true cyoobin/docker-react-app npm run test -- --coverage

      - name: Test Success
        if: success()
        run: echo "Test Success"

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: docker-react-test
          environment_name: Docker-react-test-env
          existing_bucket_name: elasticbeanstalk-ap-northeast-2-292745245601
          region: ap-northeast-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
